// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";

console.log(List.length({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }));

// look ma, regular JavaScript!
var message = "hello";
function greet(m) {
  console.log(m)
}
;

greet("me");

console.log(message);

var add = (function(a, b) {
    console.log("hello from raw JavaScript!");
    return a + b
  });

console.log(add(1, 2));

export {
  add ,
  
}
/*  Not a pure module */
