// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";
import AutoJs from "../../../src/js/auto.js";

function createAuto(prim) {
  return new AutoJs(prim);
}

var brumbrum = new AutoJs("BrumBrum");

console.log(brumbrum);

const val = { secret: "ley" }
;

console.log(val.secret);

const test = (input) => (input==="nix") ? undefined : "unleer"
;

List.map((function (wert) {
        var wert$1 = test(wert);
        if (wert$1 == null) {
          console.log("wert leer");
        } else {
          console.log("wert gefunden : " + wert$1);
        }
        
      }), {
      hd: "nix",
      tl: {
        hd: "drin",
        tl: /* [] */0
      }
    });

const values = obj => Object.values(obj)
;

var jsObject = {
  art: "test",
  gueltig: true,
  id: 284
};

console.log(jsObject.gueltig);

const obj = { name: `Rudolf`, jubeln: () => console.log(`Ich bin ${obj.name}.`)}
;

obj.name = "Vera";

obj.jubeln();

const wolf = { name: "gang", getData: (title, age, szn) =>
  `${title} wolf${wolf.name}
Alter: ${age}
Sozialversicherungsnr.: ${szn}`};
;

function func(prim, prim$1, prim$2, prim$3) {
  return prim.getData(prim$1, prim$2, prim$3);
}

var nameOfTestObjekt = func(wolf, "Herr", 54, "444");

console.log(nameOfTestObjekt);

const verpluescher = (...tiere) => tiere.map(tier => "Plüsch" + tier.toLowerCase()).join(", ")
;

console.log(verpluescher("Baer", "Hai", "Kamel", "Loewe"));

var $$default = {
  pommes: "fritz",
  ungesund: true
};

export {
  createAuto ,
  brumbrum ,
  jsObject ,
  nameOfTestObjekt ,
  $$default ,
  $$default as default,
  
}
/* brumbrum Not a pure module */
