// Generated by ReScript, PLEASE EDIT WITH CARE


const obj = { name: `Rudolf`, jubeln: () => console.log(`Ich bin ${obj.name}.`)}
;

obj.name = "Vera";

var obj2 = {
  position: 120,
  extent: 0,
  content: " dummyPosition ",
  line: 4
};

console.log(`Ich bin ${obj2.content}.`)
;

obj2.content = "Vera";

console.log(`Ich bin ${obj2.content}.`)
;

function bar(x) {
  var f = x.twoArgs;
  return f(3, "a");
}

const jsOb2 = { name: `Rudolf`, jubeln: () => console.log(`Ich bin ${jsOb2.name}.`)}
;

export {
  obj2 ,
  bar ,
  
}
/*  Not a pure module */
