// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Axios from "axios";

function recTypeToJs(param) {
  return {
          one: param.one,
          key: param.key
        };
}

function recTypeFromJs(param) {
  return {
          one: param.one,
          key: param.key
        };
}

function handleResponse(data) {
  console.log("handleResponse");
  console.log(data.one);
  console.log(data.key);
  
}

Axios.get("http://echo.jsontest.com/key/value/one/two").then(function (response) {
      return Promise.resolve(handleResponse(recTypeFromJs(response.data)));
    });

var jsObject = {
  one: "einss",
  key: "schluesselll"
};

var record = recTypeFromJs(jsObject);

console.log(record.one);

console.log(record.key);

export {
  recTypeToJs ,
  recTypeFromJs ,
  handleResponse ,
  jsObject ,
  record ,
  
}
/*  Not a pure module */
