// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../../node_modules/rescript/lib/es6/list.js";
import * as Auto from "../../../src/js/auto";
import * as Fahrrad from "../../../src/js/fahrrad";

function createAuto(prim) {
  return new Auto(prim);
}

var brumbrum = new Auto("BrumBrum");

console.log(brumbrum);

const val = { secret: "ley" }
;

console.log(val.secret);

const test = (input) => (input==="nix") ? undefined : "unleer"
;

List.map((function (wert) {
        var wert$1 = test(wert);
        if (wert$1 == null) {
          console.log("wert leer");
        } else {
          console.log("wert gefunden : " + wert$1);
        }
        
      }), {
      hd: "nix",
      tl: {
        hd: "drin",
        tl: /* [] */0
      }
    });

const values = obj => Object.values(obj)
;

var jsObject = {
  art: "test",
  gueltig: true,
  id: 284
};

console.log(jsObject.gueltig);

const obj = { name: `Rudolf`, jubeln: () => console.log(`Ich bin ${obj.name}.`)}
;

obj.name = "Vera";

const wolf = { name: "gang", getData: (title, age, szn) =>
  `${title} wolf${wolf.name}
Alter: ${age}
Sozialversicherungsnr.: ${szn}`};
;

function func(prim0, prim1, prim2, prim3) {
  return prim0.getData(prim1, prim2, prim3);
}

var nameOfTestObjekt = func(wolf, "Herr", 54, "444");

console.log(nameOfTestObjekt);

const verpluescher = (...tiere) => tiere.map(tier => "Plüsch" + tier.toLowerCase()).join(", ")
;

console.log(verpluescher("Baer", "Hai", "Kamel", "Loewe"));

var $$default = {
  pommes: "fritz",
  ungesund: true
};

function createFahrrad(prim) {
  return new Fahrrad(prim);
}

export {
  createAuto ,
  brumbrum ,
  jsObject ,
  nameOfTestObjekt ,
  $$default ,
  $$default as default,
  createFahrrad ,
  
}
/* brumbrum Not a pure module */
