// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../../node_modules/rescript/lib/es6/list.js";
import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";

function f(x, y, z) {
  console.log("x: " + x + " y: " + y + " z: " + z);
  
}

f("hallo", "wie", "gehts");

function f$1(x, y, z) {
  console.log("x: " + x);
  console.log("y: " + y);
  console.log("z: " + z);
  
}

function g(param) {
  return function (param$1) {
    return f$1(param, param$1, "z");
  };
}

function func(param, param$1) {
  return f$1("x", param, param$1);
}

Curry._2(func, "y", "z");

function greeter(greeting, persons) {
  return List.map((function (name) {
                return "" + greeting + ", " + name;
              }), persons);
}

function merryXmas(param) {
  return greeter("Merry Christmas", param);
}

var xmasWishes = greeter("Merry Christmas", {
      hd: "Alex",
      tl: {
        hd: "Sophie",
        tl: /* [] */0
      }
    });

console.log(xmasWishes);

export {
  f$1 as f,
  g ,
  greeter ,
  merryXmas ,
  xmasWishes ,
  
}
/*  Not a pure module */
