// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../../node_modules/rescript/lib/es6/list.js";
import * as $$Array from "../../../../node_modules/rescript/lib/es6/array.js";
import * as Caml_array from "../../../../node_modules/rescript/lib/es6/caml_array.js";

function logList(list) {
  console.log($$Array.of_list(list).join(", "));
  
}

var meineListe = {
  hd: "a",
  tl: {
    hd: "b",
    tl: {
      hd: "c",
      tl: /* [] */0
    }
  }
};

logList(meineListe);

var meineListe$1 = {
  hd: "anfang",
  tl: meineListe
};

logList(meineListe$1);

var meineWeitereListe = {
  hd: "Ente",
  tl: {
    hd: "gut",
    tl: {
      hd: "alles",
      tl: {
        hd: "gut",
        tl: /* [] */0
      }
    }
  }
};

var listenConcatenated = List.concat({
      hd: meineListe$1,
      tl: {
        hd: meineWeitereListe,
        tl: /* [] */0
      }
    });

logList(listenConcatenated);

var head = List.hd(listenConcatenated);

console.log(head);

var fuenfter = List.nth(listenConcatenated, 4);

console.log("fünfter : " + fuenfter);

var length = List.length(listenConcatenated);

console.log("length : " + length);

if (List.length(listenConcatenated) > 4) {
  var exit = 0;
  if (listenConcatenated) {
    var match = listenConcatenated.tl;
    if (match) {
      var match$1 = match.tl;
      if (match$1) {
        var match$2 = match$1.tl;
        if (match$2) {
          console.log("a: " + listenConcatenated.hd + ", b: " + match.hd + ", c: " + match$1.hd + ", d: " + match$2.hd);
          logList(match$2.tl);
        } else {
          exit = 1;
        }
      } else {
        exit = 1;
      }
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "datastructuresSample.res",
            68,
            6
          ],
          Error: new Error()
        };
  }
  
}

var meinArray = [
  "a",
  "b",
  "c",
  "d"
];

console.log(meinArray);

console.log(Caml_array.get(meinArray, 2));

console.log(meinArray.length);

Caml_array.set(meinArray, 3, "wurst");

console.log(meinArray);

function logJsArray(input) {
  var v = input.join(", ");
  console.log("logJsArray: " + v);
  
}

logJsArray(meinArray);

var nochnArray = [1,2,99,1000,-4];

logJsArray(nochnArray);

var haare = "überall";

var geruch = "streng";

var meAlsWerwolf = {
  haare: haare,
  geruch: geruch
};

var meinRecordObject = {
  field1: 1,
  field2: "zwei",
  field3: false,
  field4: Date.now()
};

console.log(meinRecordObject);

meinRecordObject.field3 = true;

console.log(meinRecordObject);

var logReasonArray = logJsArray;

export {
  logList ,
  meineListe$1 as meineListe,
  meineWeitereListe ,
  listenConcatenated ,
  head ,
  fuenfter ,
  length ,
  meinArray ,
  logJsArray ,
  nochnArray ,
  logReasonArray ,
  haare ,
  geruch ,
  meAlsWerwolf ,
  meinRecordObject ,
  
}
/*  Not a pure module */
