// Generated by ReScript, PLEASE EDIT WITH CARE


var p3 = "reached basement on junkLevel3";

var p2 = "further down the stairs to junkLevel2";

var p1 = "1 stage down on junkLevel1";

var p0 = "just on junkLevel0";

console.log("\npayload p0: " + p0 + "\npayload p1: " + p1 + "\npayload p2: " + p2 + "\npayload p3: " + p3 + "\n    ");

var junk = {
  payload: "just on junkLevel0",
  junkLevel1: {
    payload: "1 stage down on junkLevel1",
    junkLevel2: {
      payload: "further down the stairs to junkLevel2",
      junkLevel3: {
        payload: "reached basement on junkLevel3"
      }
    }
  }
};

export {
  junk ,
  p0 ,
  p1 ,
  p2 ,
  p3 ,
  
}
/*  Not a pure module */
