// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";
import * as Json_decode from "../../../../node_modules/@glennsl/bs-json/lib/es6_global/src/Json_decode.js";

require('isomorphic-fetch')
;

function handleResponse(json) {
  var r_one = Json_decode.field("one", Json_decode.string, json);
  var r_key = Json_decode.field("key", Json_decode.string, json);
  var key = r_one;
  console.log("\n    response ist: " + key + "\n  ");
  
}

fetch("http://echo.jsontest.com/key/value/one/two").then(function (prim) {
        return prim.json();
      }).then(function (text) {
      return Promise.resolve(handleResponse(text));
    });

require('isomorphic-fetch')
;

function dataHandler(data) {
  console.log("self defined type -> data.one : " + data.one);
  console.log("self defined type -> data.key : " + data.key);
  
}

function responseTypeToJs(param) {
  return {
          one: param.one,
          key: param.key
        };
}

function responseTypeFromJs(param) {
  return {
          one: param.one,
          key: param.key
        };
}

require('isomorphic-fetch');
;

var fetchApiResponseInline = (()=>fetch("http://echo.jsontest.com/key/value/one/two").then(r => r.json()));

function handleData(data) {
  console.log("handleData");
  console.log(data.one);
  console.log(data.key);
  
}

function parseJsonData(data) {
  return {
          one: Json_decode.field("one", Json_decode.string, data),
          key: Json_decode.field("key", Json_decode.string, data)
        };
}

Curry._1(fetchApiResponseInline, undefined).then(function (data) {
      return Promise.resolve(handleData(parseJsonData(data)));
    });

export {
  handleResponse ,
  dataHandler ,
  responseTypeToJs ,
  responseTypeFromJs ,
  fetchApiResponseInline ,
  handleData ,
  parseJsonData ,
  
}
/*  Not a pure module */
