// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";

const jsObject = {
      myName: "blabla",
      myMethod: (greeting) => console.log(`${greeting}, Mr.${jsObject.myName}`)
    };
;

console.log(jsObject.myName);

jsObject.myName = "HERBERT";

Curry._1(jsObject.myMethod, "Hello");

jsObject.myName = "Vanessa";

console.log(jsObject.myName);

export {
  
}
/*  Not a pure module */
