// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../../node_modules/rescript/lib/es6/list.js";
import * as $$Array from "../../../../node_modules/rescript/lib/es6/array.js";
import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";

function createElement(f, childrenOpt, param) {
  var children = childrenOpt !== undefined ? childrenOpt : /* [] */0;
  console.log(children);
  var reducer = function (state, item) {
    return state + Curry._1(f, item) | 0;
  };
  return List.fold_left(reducer, 0, children);
}

function make(f, children) {
  console.log(children);
  var reducer = function (state, item) {
    return state + Curry._1(f, item) | 0;
  };
  return $$Array.fold_left(reducer, 0, children);
}

export {
  createElement ,
  make ,
  
}
/* No side effect */
