// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRow from "./jsxRow.js";

var sum = JsxRow.createElement((function (x) {
        return Math.imul(x, x);
      }), {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 33,
          tl: {
            hd: 44,
            tl: {
              hd: 5,
              tl: {
                hd: 6,
                tl: /* [] */0
              }
            }
          }
        }
      }
    }, undefined);

console.log("sum: " + sum);

var sum2 = JsxRow.createElement((function (x) {
        return Math.imul(x, x);
      }), {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 33,
          tl: {
            hd: 44,
            tl: {
              hd: 5,
              tl: {
                hd: 6,
                tl: /* [] */0
              }
            }
          }
        }
      }
    }, undefined);

console.log("sum2: " + sum2);

export {
  sum ,
  sum2 ,
  
}
/* sum Not a pure module */
