// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "../../../../node_modules/rescript/lib/es6/list.js";
import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";
import * as Hashtbl from "../../../../node_modules/rescript/lib/es6/hashtbl.js";

var animals = {
  contents: Hashtbl.create(undefined, 0)
};

function addAnimal(animal) {
  return Hashtbl.add(animals.contents, animal.name, animal.species);
}

function visitAnimals(f) {
  return Hashtbl.iter((function (name, species) {
                return Curry._1(f, {
                            name: name,
                            species: species
                          });
              }), animals.contents);
}

var zooName = "Zur Schlangengrube";

var description = "Kaninchen Stall mit angeschlossenem Terrarium";

var privateStuff = [
  "private",
  "keep",
  "out"
];

var Zoo = {
  animals: animals,
  addAnimal: addAnimal,
  visitAnimals: visitAnimals,
  zooName: zooName,
  description: description,
  privateStuff: privateStuff
};

List.iter((function (param) {
        return addAnimal({
                    name: param[0],
                    species: param[1]
                  });
      }), {
      hd: [
        "Max",
        "Meerschweinchen"
      ],
      tl: {
        hd: [
          "Josef",
          "Kaninchen"
        ],
        tl: {
          hd: [
            "Maxine",
            "Maus"
          ],
          tl: {
            hd: [
              "Klara",
              "Schlange"
            ],
            tl: /* [] */0
          }
        }
      }
    });

visitAnimals(function (param) {
      console.log("name: " + param.name + " von Spezies: " + param.species);
      
    });

console.log(zooName);

console.log("ZooName: " + zooName + " und Description: " + description);

console.log("ZooName: " + zooName + " und Description: " + description);

var name = "auto von BrummBrumm Unlimited";

var Auto = {
  name: name,
  preis: 14000.99
};

var name$1 = "\"kutsche mit " + "Mr.Ed" + "\"";

var Kutsche = {
  name: name$1,
  preis: 900.77
};

var preis = 14000.99;

export {
  Zoo ,
  Auto ,
  Kutsche ,
  name ,
  preis ,
  
}
/* animals Not a pure module */
