// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "../../../../node_modules/rescript/lib/es6/pervasives.js";

var box = {
  contents: 99
};

var box2 = {
  contents: 99
};

box.contents = 100;

box2.contents = 100;

Pervasives.print_int(box.contents);

Pervasives.print_int(box.contents);

export {
  box ,
  box2 ,
  
}
/*  Not a pure module */
