// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "../../../../node_modules/rescript/lib/es6/caml_option.js";

var dirname = typeof __dirname === "undefined" ? undefined : __dirname;

var filename = typeof __filename === "undefined" ? undefined : __filename;

var _module = typeof module === "undefined" ? undefined : module;

var $$require = typeof require === "undefined" ? undefined : require;

var dirname$1 = dirname === undefined ? undefined : Caml_option.some(dirname);

var filename$1 = filename === undefined ? undefined : Caml_option.some(filename);

var _module$1 = _module === undefined ? undefined : Caml_option.some(_module);

var $$require$1 = $$require === undefined ? undefined : Caml_option.some($$require);

export {
  dirname$1 as dirname,
  filename$1 as filename,
  _module$1 as _module,
  $$require$1 as $$require,
  
}
/* dirname Not a pure module */
