// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("Mr.X");

var vanillaJsObj1 = {
  name: "Mr.Record",
  age: 22
};

console.log(vanillaJsObj1.name);

function recTestTypeToJs(param) {
  return {
          name: param.name,
          age: param.age
        };
}

function recTestTypeFromJs(param) {
  return {
          name: param.name,
          age: param.age
        };
}

var testRec1 = recTestTypeFromJs(vanillaJsObj1);

console.log(testRec1.name);

var testRec2 = {
  name: "Mrs.Record",
  age: 99
};

var testJs2 = recTestTypeToJs(testRec2);

console.log(testJs2.name);

var rec1 = {
  name: "Mr.X",
  age: 22
};

export {
  rec1 ,
  vanillaJsObj1 ,
  recTestTypeToJs ,
  recTestTypeFromJs ,
  testRec1 ,
  testRec2 ,
  testJs2 ,
  
}
/*  Not a pure module */
