// Generated by ReScript, PLEASE EDIT WITH CARE


var timer = new Promise((function (resolve, param) {
        setTimeout((function (param) {
                return resolve("Done!");
              }), 1000);
        
      }));

Promise.resolve(1).then(function (value) {
        return Promise.resolve(value + 1 | 0);
      }).then(function (value) {
      return Promise.resolve((console.log(value), undefined));
    });

Promise.resolve(1).then(function (value) {
        return Promise.resolve(value + 1 | 0);
      }).then(function (value) {
      return Promise.resolve((console.log(value), undefined));
    });

Promise.resolve(1).then(function (value) {
        return Promise.resolve(value + 1 | 0);
      }).then(function (value) {
      return Promise.resolve((console.log(value), undefined));
    });

export {
  timer ,
  
}
/* timer Not a pure module */
